name: auto build & publish

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 14
      - run: yarn install-fetch-dependencies
      - run: yarn get-data
      - run: yarn build-badgeMD
      - uses: EndBug/add-and-commit@v4
        with:
          author_name: Auto Builder
          message: 'Updated json and Version'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn install
      - run: yarn build
      - run: yarn test
      - run: yarn publish
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}